SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `perftest2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;

CREATE TABLE IF NOT EXISTS `perftest2`.`forum` (
`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`name` VARCHAR(255) NOT NULL,
`shortname` VARCHAR(255) NOT NULL,
`userEmail` VARCHAR(255) NOT NULL,
PRIMARY KEY (`shortname`),
UNIQUE INDEX `shortname_UNIQUE` (`shortname` ASC),
UNIQUE INDEX `name_UNIQUE` (`name` ASC),
UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `perftest2`.`user` (
`email` VARCHAR(255) NOT NULL,
`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`about` VARCHAR(5000) NOT NULL,
`isAnonymous` TINYINT(1) NOT NULL DEFAULT False,
`name` VARCHAR(255) NOT NULL,
`username` VARCHAR(255) NOT NULL,
UNIQUE INDEX `id_UNIQUE` (`id` ASC),
PRIMARY KEY (`email`, `id`),
UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `perftest2`.`post` (
`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`isApproved` TINYINT(1) NOT NULL DEFAULT false,
`isDeleted` TINYINT(1) NOT NULL DEFAULT false,
`isEdited` TINYINT(1) NOT NULL DEFAULT false,
`isHighlighted` TINYINT(1) NOT NULL DEFAULT true,
`isSpam` TINYINT(1) NOT NULL DEFAULT false,
`likes` INT(11) NOT NULL DEFAULT 0,
`message` VARCHAR(255) NOT NULL,
`parent` VARCHAR(255) NOT NULL,
`points` INT(11) NOT NULL DEFAULT 0,
`threadId` INT(10) UNSIGNED NOT NULL,
`date` DATETIME NOT NULL,
`forumShortname` VARCHAR(255) NOT NULL,
`userEmail` VARCHAR(255) NOT NULL,
`dislikes` INT(11) NOT NULL DEFAULT 0,
`materPath` VARCHAR(255) NOT NULL,
PRIMARY KEY (`id`),
INDEX `threadId_materPath` (`threadId` ASC, `materPath` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `perftest2`.`thread` (
`date` DATETIME NOT NULL,
`dislikes` INT(11) NOT NULL DEFAULT 0,
`forumShortname` VARCHAR(255) NOT NULL,
`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`isClosed` TINYINT(1) NOT NULL,
`isDeleted` TINYINT(1) NOT NULL,
`likes` INT(11) NOT NULL DEFAULT 0,
`message` VARCHAR(5000) NOT NULL,
`points` INT(11) NOT NULL DEFAULT 0,
`posts` INT(10) UNSIGNED NOT NULL DEFAULT 0,
`slug` VARCHAR(255) NOT NULL,
`title` VARCHAR(255) NOT NULL,
`userEmail` VARCHAR(255) NOT NULL,
PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `perftest2`.`followers` (
`followerEmail` VARCHAR(255) NOT NULL,
`followeeEmail` VARCHAR(255) NOT NULL,
`id` INT(11) NULL DEFAULT NULL AUTO_INCREMENT,
PRIMARY KEY (`followerEmail`, `followeeEmail`),
UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `perftest2`.`subscribes` (
`userEmail` VARCHAR(255) NOT NULL,
`threadId` INT(11) NOT NULL,
`id` INT(11) NULL DEFAULT NULL AUTO_INCREMENT,
PRIMARY KEY (`threadId`, `userEmail`),
UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;